export { default as PolicyHeader } from './components/PolicyHeader'
export { default as PolicySection } from './components/PolicySection'
export { default as PolicyTable } from './components/PolicyTable'
export { default as BackSection } from './components/BackSection'
export { default as Footer } from './components/Footer'
